import { CareerOption } from "./types";

export const careers: CareerOption[] = [
  {
    id: "doctor",
    name: "Bác sĩ",
    englishName: "Doctor",
    icon: "Stethoscope",
    description: "Chăm sóc sức khỏe, điều trị bệnh và mang lại nụ cười khỏe mạnh cho mọi người.",
    promptMale: "A handsome male doctor in a pristine white lab coat with a stethoscope around his neck, standing inside a modern, highly advanced hospital clinic room with clean blue-and-white lighting, smiling warmly and confidently, professional look, 8k resolution, cinematic lighting.",
    promptFemale: "A beautiful female doctor in a pristine white lab coat with a stethoscope around her neck, standing inside a modern, highly advanced hospital clinic room with clean blue-and-white lighting, smiling warmly and confidently, professional look, 8k resolution, cinematic lighting.",
    gradient: "from-emerald-50 to-teal-50 hover:from-emerald-100 hover:to-teal-100 dark:from-emerald-950/20 dark:to-teal-950/20",
    textColor: "text-teal-600 dark:text-teal-400",
    borderColor: "border-teal-200 dark:border-teal-800",
  },
  {
    id: "astronaut",
    name: "Phi hành gia",
    englishName: "Astronaut",
    icon: "Rocket",
    description: "Bay vào vũ trụ bao la, khám phá những hành tinh mới và những bí ẩn của ngân hà.",
    promptMale: "A proud male astronaut wearing a highly detailed white NASA space suit, standing in the cockpit of a futuristic space shuttle with glowing instrument panels, viewing planet Earth out of the window, cosmic stars and nebula background, epic space theme, 8k resolution.",
    promptFemale: "A proud female astronaut wearing a highly detailed white NASA space suit, standing in the cockpit of a futuristic space shuttle with glowing instrument panels, viewing planet Earth out of the window, cosmic stars and nebula background, epic space theme, 8k resolution.",
    gradient: "from-blue-50 to-indigo-50 hover:from-blue-100 hover:to-indigo-100 dark:from-blue-950/20 dark:to-indigo-950/20",
    textColor: "text-blue-600 dark:text-blue-400",
    borderColor: "border-blue-200 dark:border-blue-800",
  },
  {
    id: "teacher",
    name: "Giáo viên",
    englishName: "Teacher",
    icon: "GraduationCap",
    description: "Truyền dạy kiến thức, hướng dẫn học sinh và ươm mầm cho những tài năng tương lai.",
    promptMale: "A friendly male teacher standing proudly in front of a modern smart blackboard in a bright, colorful classroom filled with books and learning materials, wearing elegant smart casual clothes, smiling warmly, inspiring and educational theme, 8k resolution.",
    promptFemale: "A friendly female teacher standing proudly in front of a modern smart blackboard in a bright, colorful classroom filled with books and learning materials, wearing elegant smart casual clothes, smiling warmly, inspiring and educational theme, 8k resolution.",
    gradient: "from-amber-50 to-orange-50 hover:from-amber-100 hover:to-orange-100 dark:from-amber-950/20 dark:to-orange-950/20",
    textColor: "text-amber-600 dark:text-amber-400",
    borderColor: "border-amber-200 dark:border-amber-800",
  },
  {
    id: "coder",
    name: "Lập trình viên",
    englishName: "Software Engineer",
    icon: "Code2",
    description: "Viết mã nguồn để tạo ra các ứng dụng, trò chơi và giải pháp công nghệ thay đổi thế giới.",
    promptMale: "A cool male software developer sitting in front of three glowing multi-screen monitors filled with complex source code, in a modern creative tech workspace, neon blue and purple ambient lighting, headphones around neck, smiling confidently, 8k resolution, cybertech aesthetic.",
    promptFemale: "A cool female software developer sitting in front of three glowing multi-screen monitors filled with complex source code, in a modern creative tech workspace, neon blue and purple ambient lighting, headphones around neck, smiling confidently, 8k resolution, cybertech aesthetic.",
    gradient: "from-violet-50 to-purple-50 hover:from-violet-100 hover:to-purple-100 dark:from-violet-950/20 dark:to-purple-950/20",
    textColor: "text-purple-600 dark:text-purple-400",
    borderColor: "border-purple-200 dark:border-purple-800",
  },
  {
    id: "robotics",
    name: "Kỹ sư Robot",
    englishName: "Robotics Engineer",
    icon: "Cpu",
    description: "Thiết kế, chế tạo và lập trình cho những chú robot thông minh giúp đỡ con người.",
    promptMale: "A focused male robotics engineer wearing safety glasses, working on assembling a high-tech humanoid robot arm in a modern research laboratory, electronics and tools in background, blue and orange cyber lighting, professional 8k render.",
    promptFemale: "A focused female robotics engineer wearing safety glasses, working on assembling a high-tech humanoid robot arm in a modern research laboratory, electronics and tools in background, blue and orange cyber lighting, professional 8k render.",
    gradient: "from-cyan-50 to-sky-50 hover:from-cyan-100 hover:to-sky-100 dark:from-cyan-950/20 dark:to-sky-950/20",
    textColor: "text-cyan-600 dark:text-cyan-400",
    borderColor: "border-cyan-200 dark:border-cyan-800",
  },
  {
    id: "chef",
    name: "Đầu bếp trưởng",
    englishName: "Executive Chef",
    icon: "Utensils",
    description: "Sáng tạo những món ăn ngon, trang trí đẹp mắt và mang lại trải nghiệm ẩm thực tuyệt vời.",
    promptMale: "A proud male master chef wearing a crisp white chef's uniform and a tall white chef hat, standing in a gleaming professional restaurant kitchen with stainless steel counter, holding a beautifully plated gourmet dish, warm professional lighting, 8k.",
    promptFemale: "A proud female master chef wearing a crisp white chef's uniform and a tall white chef hat, standing in a gleaming professional restaurant kitchen with stainless steel counter, holding a beautifully plated gourmet dish, warm professional lighting, 8k.",
    gradient: "from-rose-50 to-pink-50 hover:from-rose-100 hover:to-pink-100 dark:from-rose-950/20 dark:to-pink-950/20",
    textColor: "text-rose-600 dark:text-rose-400",
    borderColor: "border-rose-200 dark:border-rose-800",
  },
  {
    id: "artist",
    name: "Họa sĩ",
    englishName: "Artist",
    icon: "Palette",
    description: "Vẽ nên những bức tranh ngập tràn màu sắc, truyền cảm hứng và thể hiện vẻ đẹp cuộc sống.",
    promptMale: "A talented male artist standing in a sun-drenched painting studio filled with colorful canvases and paint brushes, holding a wooden palette and brush, smiling beside a beautiful canvas painting of a sunset landscape, watercolor style highlights, 8k.",
    promptFemale: "A talented female artist standing in a sun-drenched painting studio filled with colorful canvases and paint brushes, holding a wooden palette and brush, smiling beside a beautiful canvas painting of a sunset landscape, watercolor style highlights, 8k.",
    gradient: "from-fuchsia-50 to-pink-50 hover:from-fuchsia-100 hover:to-pink-100 dark:from-fuchsia-950/20 dark:to-pink-950/20",
    textColor: "text-fuchsia-600 dark:text-fuchsia-400",
    borderColor: "border-fuchsia-200 dark:border-fuchsia-800",
  },
  {
    id: "pilot",
    name: "Phi công",
    englishName: "Pilot",
    icon: "Plane",
    description: "Điều khiển những chiếc chuyên cơ hiện đại, đưa hành khách bay qua những chân trời mới.",
    promptMale: "An elegant male airline pilot in a crisp dark blue uniform with golden epaulets and a pilot cap, sitting in a high-tech modern cockpit with numerous glowing navigation screens, beautiful sunny clouds visible outside the airplane window, 8k.",
    promptFemale: "An elegant female airline pilot in a crisp dark blue uniform with golden epaulets and a pilot cap, sitting in a high-tech modern cockpit with numerous glowing navigation screens, beautiful sunny clouds visible outside the airplane window, 8k.",
    gradient: "from-sky-50 to-blue-50 hover:from-sky-100 hover:to-blue-100 dark:from-sky-950/20 dark:to-blue-950/20",
    textColor: "text-sky-600 dark:text-sky-400",
    borderColor: "border-sky-200 dark:border-sky-800",
  },
  {
    id: "scientist",
    name: "Nhà khoa học",
    englishName: "Scientist",
    icon: "FlaskConical",
    description: "Nghiên cứu các định luật tự nhiên, làm thí nghiệm hóa học để tìm ra những phát minh vĩ đại.",
    promptMale: "A smart male research scientist wearing lab safety goggles and a white coat, looking through a microscope in a clean, modern biochemistry laboratory, with colorful glowing test tubes and scientific equipment in background, 8k.",
    promptFemale: "A smart female research scientist wearing lab safety goggles and a white coat, looking through a microscope in a clean, modern biochemistry laboratory, with colorful glowing test tubes and scientific equipment in background, 8k.",
    gradient: "from-indigo-50 to-violet-50 hover:from-indigo-100 hover:to-violet-100 dark:from-indigo-950/20 dark:to-violet-950/20",
    textColor: "text-indigo-600 dark:text-indigo-400",
    borderColor: "border-indigo-200 dark:border-indigo-800",
  },
  {
    id: "firefighter",
    name: "Lính cứu hỏa",
    englishName: "Firefighter",
    icon: "ShieldAlert",
    description: "Dũng cảm chiến đấu với lửa để bảo vệ cuộc sống bình yên và tài sản của mọi người.",
    promptMale: "A heroic male firefighter in a detailed red-and-yellow protective bunker gear suit and heavy helmet, holding a water hose confidently, with a clean red firetruck and water mist in the background under soft atmospheric dramatic lighting, 8k.",
    promptFemale: "A heroic female firefighter in a detailed red-and-yellow protective bunker gear suit and heavy helmet, holding a water hose confidently, with a clean red firetruck and water mist in the background under soft atmospheric dramatic lighting, 8k.",
    gradient: "from-red-50 to-orange-50 hover:from-red-100 hover:to-orange-100 dark:from-red-950/20 dark:to-orange-950/20",
    textColor: "text-red-600 dark:text-red-400",
    borderColor: "border-red-200 dark:border-red-800",
  },
];
